import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root,'data',name),'utf8').replace(/^\uFEFF/,''));
const profile = read('profile.json'), papers = read('publications.json').filter(p=>p.isFirstAuthor), news = read('news.json'), honors = read('honors.json');
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external = (url,text,cls='') => `<a href="${esc(url)}"${cls?` class="${cls}"`:''} target="_blank" rel="noopener noreferrer">${text}</a>`;
const icons={mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',scholar:'<path d="m2 9 10-5 10 5-10 5Z"/><path d="M6 11v6c3 3 9 3 12 0v-6M22 9v8"/>',github:'<path d="M9 19c-4 1-4-2-6-2m12 5v-4a3 3 0 0 0-1-2c4 0 7-2 7-6a5 5 0 0 0-1-3 5 5 0 0 0 0-4s-2 0-4 2a13 13 0 0 0-8 0C6 3 4 3 4 3a5 5 0 0 0 0 4 5 5 0 0 0-1 3c0 4 3 6 7 6a3 3 0 0 0-1 2v4"/>',orcid:'<circle cx="12" cy="12" r="9"/><path d="M8 10v7m4-7h2a3.5 3.5 0 0 1 0 7h-2ZM8 7h.01"/>',university:'<path d="m3 8 9-5 9 5M3 9h18M3 21h18M5 10v8m5-8v8m4-8v8m5-8v8M2 18h20"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',light:'<path d="M8 17v-2a7 7 0 1 1 8 0v2m-8 1h8m-7 3h6"/>',award:'<circle cx="12" cy="8" r="5"/><path d="m8 12-2 9 6-3 6 3-2-9"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.arrow}</svg>`;
function head(title,route=''){
 const prefix=route?'../':'';
 const description='Qingxiao Huang (黄青霄), PhD student at City University of Hong Kong. Research in wireless communications, RIS, holographic MIMO, and near-field communications.';
 return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Qingxiao Huang</title><meta name="description" content="${esc(description)}"><meta name="author" content="Qingxiao Huang"><meta name="theme-color" content="#21334a"><link rel="canonical" href="${profile.siteUrl}/${route}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} | Qingxiao Huang"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${profile.siteUrl}/${route}"><meta property="og:image" content="${profile.siteUrl}/assets/profile.jpg"><meta name="twitter:card" content="summary"><link rel="icon" href="${prefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}styles.css"><script src="${prefix}script.js" defer></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:profile.name,alternateName:profile.chineseName,url:profile.siteUrl,image:profile.siteUrl+'/assets/profile.jpg',jobTitle:profile.role,affiliation:{'@type':'CollegeOrUniversity',name:profile.affiliation},sameAs:[profile.scholar,profile.orcid,profile.cityu,profile.github],knowsAbout:profile.interests})}</script></head><body><a class="skip-link" href="#main-content">Skip to content</a>`;
}
function nav(sub=false){const base=sub?'../index.html':'';const items=[['about','About'],['research','Research'],['news','News'],['publications','Publications'],['honors','Honors'],...(profile.service.length?[['service','Service']]:[]),['education','Education'],['contact','Contact']];return `<header class="top-nav"><div class="nav-inner"><a class="brand" href="${base||'./'}" aria-label="Qingxiao Huang, home">Qingxiao Huang<span class="brand-dot">.</span></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="main-nav">${icon('menu')}</button><nav id="main-nav" aria-label="Main navigation">${items.map(([id,t])=>`<a href="${base}#${id}">${t}</a>`).join('')}</nav></div></header>`;}
const footer=()=>`<footer class="site-footer"><p>© <span id="current-year">2026</span> Qingxiao Huang · 黄青霄</p><p>Updated September 2026 <span aria-hidden="true">·</span> Built on ${external('https://github.com/yihangtao/AcaNova-X','AcaNova-X')} <span aria-hidden="true">·</span> ${external('https://github.com/qxhuang0322/qxhuang0322.github.io','Source')}</p><a class="back-top" href="#" aria-label="Back to top">↑</a></footer></body></html>`;
const heading=(id,title,href,label='View all')=>`<div class="section-heading"><h2 id="${id}-title">${title}</h2>${href?`<a class="view-link" href="${href}">${label} ${icon('arrow')}</a>`:''}</div>`;
function socials(){const links=[['mail',`mailto:${profile.email}`,'Email'],['scholar',profile.scholar,'Google Scholar'],['orcid',profile.orcid,'ORCID'],['university',profile.cityu,'CityU Scholars'],['github',profile.github,'GitHub']];return `<div class="social-links">${links.map(([i,url,label])=>`<a class="social-link" href="${esc(url)}" aria-label="${label}" title="${label}"${i!=='mail'?' target="_blank" rel="noopener noreferrer"':''}>${icon(i)}<span class="social-tooltip">${label}</span></a>`).join('')}</div>`;}
function publicationFigure(p,sub=false){
 if(!p.thumbnail)return '';
 const src=(sub?'../':'')+p.thumbnail;
 return `<figure class="paper-art"><a class="paper-figure-link" href="${esc(src)}" target="_blank" rel="noopener noreferrer" aria-label="Open original figure from ${esc(p.title)}"><img src="${esc(src)}" alt="${esc(p.thumbnailAlt||'System diagram from '+p.title)}" loading="lazy" decoding="async"></a><figcaption><span>${esc(p.figureLabel||'Paper figure')}</span>${external(p.figureSource||p.links[0].url,'From paper ↗')}</figcaption></figure>`;
}
function publication(p,sub=false){const authors=p.authors.map(a=>a==='Qingxiao Huang'?`<strong>${esc(a)}</strong>`:esc(a)).join(', ');return `<article class="publication" data-status="${p.status}" data-search="${esc([p.title,...p.authors,p.venue,p.year].join(' ').toLowerCase())}">${publicationFigure(p,sub)}<div class="paper-body"><div class="paper-meta"><span class="venue-badge${p.status==='preprint'?' preprint':''}">${esc(p.status==='preprint'?'Preprint':p.venueShort)}</span><span>${p.year}</span>${p.status!=='preprint'&&p.journalImpactFactor?external(p.journalImpactFactor.sourceUrl,`WoS JIF ${esc(p.journalImpactFactor.value)} (${p.journalImpactFactor.year})`,'impact-factor'):''}</div><h3>${external(p.links[0].url,esc(p.title))}</h3><p class="paper-authors">${authors}</p><p class="paper-venue">${esc(p.venue)}${p.status==='accepted'?' · Accepted':''}</p>${p.summary?`<p class="paper-summary">${esc(p.summary)}</p>`:''}<div class="paper-links">${p.links.map(l=>external(l.url,esc(l.label)+' <span aria-hidden="true">↗</span>','paper-link')).join('')}</div></div></article>`;}
const newsList=list=>`<ol class="news-list">${list.map(n=>`<li><time>${esc(n.date)}</time><div>${n.content}${n.url?' '+external(n.url,'Details ↗','inline-source'):''}</div></li>`).join('')}</ol>`;
const honorsList=list=>`<ol class="honors-list">${list.map(h=>`<li><span class="honor-year">${esc(h.date)}</span><div><h3>${h.url?external(h.url,esc(h.title)):esc(h.title)}</h3><p>${esc(h.org||h.description)}</p></div>${icon('award')}</li>`).join('')}</ol>`;
function home(){
 const html=`${head('Academic Homepage')}${nav()}<main class="layout" id="main-content"><aside class="profile-column"><div class="profile-card"><img class="portrait" src="assets/profile.jpg" width="224" height="220" alt="Portrait of Qingxiao Huang" fetchpriority="high"><h1>${profile.name}<span lang="zh-Hans">${profile.chineseName}</span></h1><p class="profile-role">${profile.role}</p><p class="profile-affiliation">${external('https://www.cityu.edu.hk/',profile.affiliation)}</p><p class="profile-lab">${external(profile.lab,'JC STEM Lab of Smart City')}</p>${socials()}<div class="interests"><h2>${icon('light')} Research Interests</h2><ul>${profile.interests.map((s,i)=>`<li><span class="interest-mark" aria-hidden="true">${['◈','▦','◎','⌁'][i]}</span>${esc(s)}</li>`).join('')}</ul></div><a class="profile-email" href="mailto:${profile.email}">${icon('mail')}${profile.email}</a></div></aside><div class="main-column">
 <section id="about" aria-labelledby="about-title">${heading('about','About Me')}<div class="biography">${profile.about.map(p=>`<p>${p}</p>`).join('')}</div><div class="collaboration-note">${icon('light')}<p><strong>Open to collaboration.</strong> I enjoy exchanging ideas and working with researchers on wireless communications and intelligent networks. Feel free to <a href="mailto:${profile.email}">get in touch</a>.</p></div></section>
 <section id="research" aria-labelledby="research-title">${heading('research','Research Overview')}<div class="research-grid">${profile.research.map(r=>`<article class="research-card"><div class="research-card-top"><span class="research-symbol" aria-hidden="true">${r.code==='HMIMO'?'◎':r.code==='RIS'?'▦':'⌁'}</span><span class="research-code">${r.code}</span></div><h3>${r.title}</h3><p>${r.description}</p></article>`).join('')}</div></section>
 <section id="news" aria-labelledby="news-title">${heading('news','Latest News','pages/all-news.html')}${newsList(news.slice(0,5))}</section>
 <section id="publications" aria-labelledby="publications-title">${heading('publications','Selected Publications','pages/all-publications.html','Full publication list')}<p class="section-intro">Selected work on intelligent surfaces, wireless power, and holographic MIMO.</p><div class="publications-list">${papers.filter(p=>p.featured).map(p=>publication(p)).join('')}</div><a class="text-link" href="pages/all-publications.html">Explore all ${papers.length} publications ${icon('arrow')}</a></section>
 <section id="honors" aria-labelledby="honors-title">${heading('honors','Honors & Awards','pages/all-honors.html')}${honorsList(honors.slice(0,5))}</section>
 ${profile.service.length?`<section id="service" aria-labelledby="service-title">${heading('service','Academic Service')}<div class="service-grid">${profile.service.map(s=>`<article><h3>${esc(s.title)}</h3><ul>${s.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}</div></section>`:''}
 <section id="education" aria-labelledby="education-title">${heading('education','Education')}<ol class="education-list">${profile.education.map(e=>`<li><span class="school-mark ${e.color}" aria-hidden="true">${e.code}</span><div><div class="education-top"><h3>${esc(e.degree)}</h3><time>${e.dates}</time></div><p class="institution">${external(e.url,esc(e.institution))}</p><p class="education-detail">${esc(e.detail)}</p></div></li>`).join('')}</ol></section>
 <section id="contact" aria-labelledby="contact-title">${heading('contact','Contact')}<div class="contact-card"><div>${icon('mail')}<div><h3>Email</h3><a href="mailto:${profile.email}">${profile.email}</a></div></div><div>${icon('pin')}<div><h3>Affiliation</h3><p>Department of Computer Science<br>City University of Hong Kong<br>Tat Chee Avenue, Kowloon, Hong Kong SAR</p></div></div><div class="contact-bottom">Find my latest work on ${external(profile.scholar,'Google Scholar')} and ${external(profile.cityu,'CityU Scholars')}.</div></div></section></div></main>${footer()}`;
 fs.writeFileSync(path.join(root,'index.html'),html);
}
function subpage(type,title,description,content){const route=`pages/all-${type}.html`;fs.writeFileSync(path.join(root,route),`${head(title,route)}${nav(true)}<main id="main-content" class="subpage"><a class="breadcrumb" href="../index.html">← Back to homepage</a><div class="page-heading"><p class="eyebrow">QINGXIAO HUANG</p><h1>${title}</h1><p>${description}</p></div>${content}</main>${footer()}`);}
home();
subpage('publications','Publications','Research in wireless communications, intelligent surfaces, and holographic MIMO.',`<div class="publication-tools"><div class="filters" role="group" aria-label="Filter publications"><button data-filter="all" aria-pressed="true">All <span>${papers.length}</span></button><button data-filter="published" aria-pressed="false">Published</button><button data-filter="preprint" aria-pressed="false">Preprints</button></div><label class="search-label"><span class="sr-only">Search publications</span><input id="publication-search" type="search" placeholder="Search title, author, or year…" autocomplete="off"></label></div><p id="publication-count" role="status" aria-live="polite">${papers.length} publications</p><div class="publications-list" id="all-publications">${papers.map(p=>publication(p,true)).join('')}</div><p class="empty-state" hidden>No matching publications. Try another search or filter.</p><p class="publication-note">Preprints are explicitly labeled. For the latest citation metrics, visit ${external(profile.scholar,'Google Scholar')}.</p>`);
subpage('news','News','Research updates and academic milestones.',newsList(news));
subpage('honors','Honors & Awards','Selected scholarships and academic recognition.',honorsList(honors));
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','pages/all-publications.html','pages/all-news.html','pages/all-honors.html'].map(p=>`<url><loc>${profile.siteUrl}/${p}</loc><lastmod>${profile.updated}</lastmod></url>`).join('')}</urlset>`);
console.log(`Built homepage and 3 archive pages with ${papers.length} publications, ${honors.length} honors, and ${news.length} news items.`);
